apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: amqp-celery-eventsource
  namespace: argo-events
spec:
  amqp:
    taskEvents:
      url: amqp://rabbitmq.karaoke.svc.cluster.local:5672
      jsonBody: true
      exchangeName: celeryev
      exchangeType: topic
      routingKey: task.succeeded
      connectionBackoff:
        duration: 10s
        steps: 5
        factor: 2
        jitter: 0.2
      queueDeclare:
        name: karaoke-celery-events
        durable: true
        autoDelete: false
        exclusive: false
        noWait: false
      queueBind:
        noWait: false
      consume:
        consumerTag: argo-events-celery-events
        autoAck: true
        exclusive: false
        noLocal: false
        noWait: false
      auth:
        username:
          name: rabbitmq-secret
          key: username
        password:
          name: rabbitmq-secret
          key: password
