"""Collectors that stage lower-trust lyrics candidates for review."""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Iterable, Optional

import requests

from .lyrics import Lyrics
from .staging import stage_lyrics
from .youtube import fetch_metadata, parse_youtube_title

_TIME_RE = re.compile(
    r"(?:(?:\d{2}:)?\d{2}:\d{2}\.\d{3}\s+-->\s+(?:\d{2}:)?\d{2}:\d{2}\.\d{3}).*"
)
_TAG_RE = re.compile(r"<[^>]+>")


@dataclass(frozen=True)
class StagedSourceResult:
    """Result from staging one external lyrics candidate."""

    staged_id: int
    artist: str
    title: str
    source_kind: str
    source_url: str
    lines: int


def _vtt_to_plain(text: str) -> str:
    """Convert WebVTT/SRV-ish captions into plain lyric-like lines."""
    out: list[str] = []
    seen: set[str] = set()
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line == "WEBVTT" or line.startswith(("Kind:", "Language:")):
            continue
        if _TIME_RE.match(line) or line.isdigit() or line.startswith("NOTE"):
            continue
        line = _TAG_RE.sub("", line)
        line = line.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
        line = re.sub(r"\s+", " ", line).strip()
        # Auto-captions often repeat incremental partial lines. Keep first exact
        # occurrence only; reviewers can still reject weak candidates.
        if line and line not in seen:
            seen.add(line)
            out.append(line)
    return "\n".join(out)


def _caption_tracks(info: Any, languages: Iterable[str]) -> list[dict]:
    """Return preferred manual/automatic caption track dicts from yt-dlp info."""
    tracks: list[dict] = []
    language_order = list(languages)
    for key in ("subtitles", "automatic_captions"):
        captions = info.get(key) or {}
        for lang in language_order:
            entries = captions.get(lang) or []
            vtt = next((e for e in entries if e.get("ext") in {"vtt", "srv3", "ttml"}), None)
            if vtt and vtt.get("url"):
                item = dict(vtt)
                item["kind"] = "manual" if key == "subtitles" else "automatic"
                item["language"] = lang
                tracks.append(item)
    return tracks


def stage_youtube_captions(
    url: str,
    *,
    languages: Iterable[str] = ("en", "nl"),
    cookies_from_browser: Optional[str] = None,
    cookies_file: Optional[str] = None,
) -> StagedSourceResult:
    """Fetch YouTube captions and stage them as unapproved plain lyrics.

    This intentionally stages, rather than approving, because captions may be
    autogenerated, contain non-lyric speech, or have metadata mismatches.
    """
    # fetch_metadata already handles the yt-dlp optional import and auth options.
    meta = fetch_metadata(
        url,
        download=False,
        cookies_from_browser=cookies_from_browser,
        cookies_file=cookies_file,
    )
    raw_title = meta["title"]
    if not raw_title:
        raise RuntimeError("yt-dlp returned no title for this YouTube URL")
    artist, title = parse_youtube_title(raw_title, meta.get("uploader") or "")

    try:
        from yt_dlp import YoutubeDL  # type: ignore
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("YouTube caption staging needs yt-dlp installed") from exc

    opts: dict[str, Any] = {"quiet": True, "no_warnings": True, "skip_download": True, "noplaylist": True}
    # Reuse the public helper indirectly through fetch_metadata would not expose
    # the full info dict, so mirror cookie options via youtube._cookie_opts.
    from .youtube import _cookie_opts
    opts.update(_cookie_opts(cookies_from_browser, cookies_file))
    with YoutubeDL(opts) as ydl:
        info = ydl.extract_info(url, download=False)

    tracks = _caption_tracks(info, languages)
    if not tracks:
        raise RuntimeError("no YouTube captions found for the requested languages")

    track = tracks[0]
    response = requests.get(track["url"], timeout=20)
    response.raise_for_status()
    plain = _vtt_to_plain(response.text)
    if not plain:
        raise RuntimeError("caption track was empty after cleanup")

    kind = f"youtube_caption_{track['kind']}_{track['language']}"
    staged_id = stage_lyrics(
        artist, title, Lyrics(plain=plain, source=kind),
        duration=meta.get("duration"), source_kind=kind, source_url=url,
        confidence=0.45 if track["kind"] == "automatic" else 0.65,
        notes="Staged from YouTube captions; review before approving.",
    )
    return StagedSourceResult(
        staged_id=staged_id, artist=artist, title=title, source_kind=kind,
        source_url=url, lines=len(plain.splitlines()),
    )
