"""Collectors that stage lower-trust lyrics candidates for review."""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Iterable, Optional

import requests

from .caption_sync import CaptionAvailability, json3_to_lrc, probe_captions
from .lyrics import Lyrics, parse_lrc
from .staging import stage_lyrics
from .youtube import fetch_metadata, parse_youtube_title

_TIME_RE = re.compile(
    r"(?:(?:\d{2}:)?\d{2}:\d{2}\.\d{3}\s+-->\s+(?:\d{2}:)?\d{2}:\d{2}\.\d{3}).*"
)
_TAG_RE = re.compile(r"<[^>]+>")


@dataclass(frozen=True)
class StagedSourceResult:
    """Result from staging one external lyrics candidate."""

    staged_id: int
    artist: str
    title: str
    source_kind: str
    source_url: str
    lines: int


def _vtt_to_plain(text: str) -> str:
    """Convert WebVTT/SRV-ish captions into plain lyric-like lines."""
    out: list[str] = []
    seen: set[str] = set()
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line == "WEBVTT" or line.startswith(("Kind:", "Language:")):
            continue
        if _TIME_RE.match(line) or line.isdigit() or line.startswith("NOTE"):
            continue
        line = _TAG_RE.sub("", line)
        line = line.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
        line = re.sub(r"\s+", " ", line).strip()
        # Auto-captions often repeat incremental partial lines. Keep first exact
        # occurrence only; reviewers can still reject weak candidates.
        if line and line not in seen:
            seen.add(line)
            out.append(line)
    return "\n".join(out)


def _caption_tracks(info: Any, languages: Iterable[str]) -> list[dict]:
    """Return preferred manual/automatic caption track dicts from yt-dlp info."""
    tracks: list[dict] = []
    language_order = list(languages)
    for key in ("subtitles", "automatic_captions"):
        captions = info.get(key) or {}
        for lang in language_order:
            entries = captions.get(lang) or []
            vtt = next((e for e in entries if e.get("ext") in {"vtt", "srv3", "ttml"}), None)
            if vtt and vtt.get("url"):
                item = dict(vtt)
                item["kind"] = "manual" if key == "subtitles" else "automatic"
                item["language"] = lang
                tracks.append(item)
    return tracks


def check_youtube_captions(
    url: str,
    *,
    languages: Iterable[str] = ("en", "en-orig", "nl"),
    cookies_from_browser: Optional[str] = None,
    cookies_file: Optional[str] = None,
) -> "CaptionAvailability":
    """Report which caption tracks a YouTube video offers, without staging."""
    try:
        from yt_dlp import YoutubeDL  # type: ignore
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("caption detection needs yt-dlp installed") from exc

    from .youtube import _cookie_opts

    opts: dict[str, Any] = {
        "quiet": True, "no_warnings": True, "skip_download": True, "noplaylist": True,
    }
    opts.update(_cookie_opts(cookies_from_browser, cookies_file))
    with YoutubeDL(opts) as ydl:
        info = ydl.extract_info(url, download=False)
    return probe_captions(info, languages)


def stage_youtube_captions(
    url: str,
    *,
    languages: Iterable[str] = ("en", "en-orig", "nl"),
    cookies_from_browser: Optional[str] = None,
    cookies_file: Optional[str] = None,
) -> StagedSourceResult:
    """Fetch YouTube captions and stage them as unapproved lyrics.

    When the caption track is available in ``json3`` the cue timings are kept,
    producing *synced* LRC lyrics (karaoke-ready) instead of a flat block of
    text. Other formats degrade to plain lyrics.

    This intentionally stages, rather than approves, because captions may be
    autogenerated, contain non-lyric speech, or have metadata mismatches.
    """
    # fetch_metadata already handles the yt-dlp optional import and auth options.
    meta = fetch_metadata(
        url,
        download=False,
        cookies_from_browser=cookies_from_browser,
        cookies_file=cookies_file,
    )
    raw_title = meta["title"]
    if not raw_title:
        raise RuntimeError("yt-dlp returned no title for this YouTube URL")
    artist, title = parse_youtube_title(raw_title, meta.get("uploader") or "")

    try:
        from yt_dlp import YoutubeDL  # type: ignore
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("YouTube caption staging needs yt-dlp installed") from exc

    opts: dict[str, Any] = {"quiet": True, "no_warnings": True, "skip_download": True, "noplaylist": True}
    # Reuse the public helper indirectly through fetch_metadata would not expose
    # the full info dict, so mirror cookie options via youtube._cookie_opts.
    from .youtube import _cookie_opts
    opts.update(_cookie_opts(cookies_from_browser, cookies_file))
    with YoutubeDL(opts) as ydl:
        info = ydl.extract_info(url, download=False)

    availability = probe_captions(info, languages)
    track = availability.best
    if track is None:
        raise RuntimeError("no YouTube captions found for the requested languages")

    response = requests.get(track.url, timeout=20)
    response.raise_for_status()
    # YouTube serves an HTML error page (HTTP 429) when rate limited; that is
    # not a caption payload and must not be misread as "captions were empty".
    content_type = response.headers.get("Content-Type", "")
    if "html" in content_type.lower() or response.text.lstrip().startswith("<"):
        raise RuntimeError(
            "YouTube returned an HTML error page instead of captions "
            "(likely rate limited); retry later or use --cookies-from-browser"
        )

    synced = ""
    if track.ext == "json3":
        try:
            synced = json3_to_lrc(response.text)
        except ValueError:
            synced = ""

    if synced:
        lines = parse_lrc(synced)
        plain = "\n".join(text for _, text in lines)
        lyrics = Lyrics(plain=plain, synced_raw=synced, lines=lines)
        line_count = len(lines)
    else:
        plain = _vtt_to_plain(response.text)
        lyrics = Lyrics(plain=plain)
        line_count = len(plain.splitlines())

    if not (lyrics.synced_raw or lyrics.plain):
        raise RuntimeError("caption track was empty after cleanup")

    sync_tag = "synced" if synced else "plain"
    kind = f"youtube_caption_{track.kind}_{track.language}_{sync_tag}"
    lyrics.source = kind

    # Manual captions are usually the real lyrics; synced timing adds value.
    confidence = 0.65 if track.kind == "manual" else 0.45
    if synced:
        confidence += 0.1

    staged_id = stage_lyrics(
        artist, title, lyrics,
        duration=meta.get("duration"), source_kind=kind, source_url=url,
        confidence=round(confidence, 2),
        notes=(
            f"Staged from {track.kind} YouTube captions "
            f"({'synced LRC from cue timings' if synced else 'plain text'}); "
            "review before approving."
        ),
    )
    return StagedSourceResult(
        staged_id=staged_id, artist=artist, title=title, source_kind=kind,
        source_url=url, lines=line_count,
    )
